
export const USER_SIGNIN_REQUEST ="USER_SIGNIN_REQUEST"
export const USER_SIGNIN_SUCESS ="USER_SIGNIN_SUCESS"
export const USER_SIGNIN_ERROR ="USER_SIGNIN_ERROR"
export const USER_SIGNOUT_REQUEST ="USER_SIGNOUT_REQUEST"

export const USER_REGISTER_REQUEST ="USER_REGISTER_REQUEST"
export const USER_REGISTER_SUCESS ="USER_REGISTER_SUCESS"
export const USER_REGISTER_ERROR ="USER_REGISTER_ERROR"
